export type purchaseListRespone = {
    value: purchaseHrd[]
}
export type purchaseHrd = {
    id: string
    number: string
    orderDate: string
    postingDate: string
    vendorId: string
    vendorNumber: string
    vendorName: string
    payToName: string
    payToVendorId: string
    payToVendorNumber: string
    shipToName: string
    shipToContact: string
    buyFromAddressLine1: string
    buyFromAddressLine2: string
    buyFromCity: string
    buyFromCountry: string
    buyFromState: string
    buyFromPostCode: string
    payToAddressLine1: string
    payToAddressLine2: string
    payToCity: string
    payToCountry: string
    payToState: string
    payToPostCode: string
    shipToAddressLine1: string
    shipToAddressLine2: string
    shipToCity: string
    shipToCountry: string
    shipToState: string
    shipToPostCode: string
    shortcutDimension1Code: string
    shortcutDimension2Code: string
    currencyId: string
    currencyCode: string
    pricesIncludeTax: boolean
    paymentTermsId: string
    shipmentMethodId: string
    purchaser: string
    requestedReceiptDate: string
    discountAmount: number
    discountAppliedBeforeTax: boolean
    totalAmountExcludingTax: number
    totalTaxAmount: number
    totalAmountIncludingTax: number
    fullyReceived: boolean
    status: string
    lastModifiedDateTime: string
    purchaseOrderLines: PurchaseOrderLines[]
}
export type PurchaseOrderLines = {
    id: string
    documentId: string
    sequence: number
    itemId: string
    accountId: string
    lineType: string
    lineObjectNumber: string
    description: string
    unitOfMeasureId: string
    unitOfMeasureCode: string
    quantity: number
    directUnitCost: number
    discountAmount: number
    discountPercent: number
    discountAppliedBeforeTax: boolean
    amountExcludingTax: number
    taxCode: string
    taxPercent: number
    totalTaxAmount: number
    amountIncludingTax: number
    invoiceDiscountAllocation: number
    netAmount: number
    netTaxAmount: number
    netAmountIncludingTax: number
    expectedReceiptDate: string
    receivedQuantity: number
    invoicedQuantity: number
    invoiceQuantity: number
    receiveQuantity: number
    itemVariantId: string
    locationId: string
}